Disable automatic allocation of THPs
THP = transparent huge page, I just needed to keep the commit headline
under 50 characters.

We hope that this will reduce the frequency of some memory
cgroup-related lockups.

This doesn't work on bosh lite, because the "VM" is a privileged
container with sysfs mounted read-only.

[#153312129]

diff --git a/jobs/garden/templates/bin/garden_start.erb b/jobs/garden/templates/bin/garden_start.erb
--- a/jobs/garden/templates/bin/garden_start.erb
+++ b/jobs/garden/templates/bin/garden_start.erb
@@ -25,6 +25,10 @@ ${BASE_PATH}/<%= p("grootfs.driver") %>-setup
   load_apparmor_profile "$GARDEN_CONFIG_DIR"/garden-default
 <% end %>
 
+if ! echo madvise > /sys/kernel/mm/transparent_hugepage/enabled ; then
+  echo "Could not disable automatic transparent hugepage allocation. This is normal in bosh lite."
+fi
+
 echo 1 > /proc/sys/kernel/dmesg_restrict
 
 ulimit -n 65536
