Add extra logging in system-preparation
Allowing or denying all by writing 'a' to devices.allow or devices.deny will
not be possible once the device cgroups has children.

When gdn starts, it creates the child garden cgroup which gets preserved over
restarts and so it makes writing to the devices.allow file impossible.

When running in systemd we will never observe this behaviour because systemd
recreates the cgroups on garden's restart.

[#163617086]
Co-authored-by: Danail Branekov <danailster@gmail.com>

diff --git a/src/greenskeeper/scripts/system-preparation b/src/greenskeeper/scripts/system-preparation
--- a/src/greenskeeper/scripts/system-preparation
+++ b/src/greenskeeper/scripts/system-preparation
@@ -23,7 +23,10 @@ function permit_device_control() {
   fi
 
   # permit our cgroup to do everything with all devices
-  (echo a > /tmp/devices-cgroup${devices_subdir}/devices.allow) 2>&1 || true
+  if ! echo a > /tmp/devices-cgroup${devices_subdir}/devices.allow && [ ! -d "/run/systemd/system" ]; then
+    # ensure this log line goes to stderr
+      >&2 echo "Could not permit all devices. This is normal in non systemd mode."
+  fi
 
   if mountpoint /tmp/devices-cgroup &> /dev/null; then
     umount /tmp/devices-cgroup 2>&1 || true
