clean up stop function in bosh ctl script
* always exit with 0 if the process is sucessfully killed
* clean up pid file is process is successfully killed
* send each kill signal only once, then wait for process to die

Signed-off-by: Craig Furman <cfurman@pivotal.io>

diff --git a/jobs/garden/templates/garden_ctl.erb b/jobs/garden/templates/garden_ctl.erb
--- a/jobs/garden/templates/garden_ctl.erb
+++ b/jobs/garden/templates/garden_ctl.erb
@@ -87,6 +87,54 @@ function set_graph_permissions() {
   chmod 750 "$graph_path"
 }
 
+function wait_pid() {
+  pid=$1
+  shift
+  max_checks=$1
+  shift
+
+  checks=$max_checks
+  while [ -e "/proc/$pid" ]; do
+    checks=$((checks - 1))
+    if [ $checks -le 0 ]; then
+      return 1
+    fi
+    sleep 0.1
+  done
+
+  return 0
+}
+
+function stop_guardian() {
+  local pid
+  setup
+  pid=$(cat "$PIDFILE")
+
+  echo "stopping guardian"
+  kill -TERM "$pid"
+  if wait_pid "$pid" 100 ; then
+    rm "$PIDFILE"
+    return 0
+  fi
+
+  echo "unable to stop guardian process using SIGTERM after 10 seconds, will now attempt to SIGQUIT"
+  kill -QUIT "$pid" || true
+  if wait_pid "$pid" 50 ; then
+    rm "$PIDFILE"
+    return 0
+  fi
+
+  echo "unable to stop guardian process using SIGQUIT after 5 seconds, will now attempt to SIGKILL"
+  kill -KILL "$pid" || true
+  if wait_pid "$pid" 50 ; then
+    rm "$PIDFILE"
+    return 0
+  fi
+
+  echo "unable to stop guardian process using SIGKILL after 5 seconds"
+  return 1
+}
+
 case $1 in
 
   start)
@@ -241,28 +289,7 @@ case $1 in
     ;;
 
   stop)
-    setup
-    pid=$(cat $PIDFILE)
-
-    for i in $(seq 30); do
-      echo "sending TERM to ${pid}..."
-      if kill $pid; then
-        sleep 1
-      else
-        echo "exited"
-        exit 0
-      fi
-    done
-
-    echo "timed out; sending SIGQUIT followed by SIGKILL to ${pid}..."
-    if kill -QUIT $pid; then
-      sleep 5
-
-      echo "killing ${pid}..."
-      kill -9 $pid
-    fi
-
-    echo "killed"
+    stop_guardian
 
     ;;
 
